name: Terraform Feature Pipeline

on:
  push:
    branches:
      - feature

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Feature Pipeline
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.1"

      - name: Terraform Version
        run: terraform version

      # Azure Authentication
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ 34878fb5-d326-48b0-b4cf-269651f4b945 }}
          tenant-id: ${{ 49d9d716-d5ad-40fa-9707-f8d27b7cd8c8 }}
          subscription-id: ${{ 990d8adf-a227-429c-918d-352714086c0e }}
          client-secret: ${{ Vl~8Q~Rhlx_CRhSiNmevf0uJ6ZHBJhgByyfMgbN- }}

      # Verify Azure authentication
      - name: Verify Azure Login
        run: |
          az account show

      # Terraform Init
      - name: Terraform Init
        working-directory: Environment/prod
        run: |
          terraform init

      # Terraform Format
      - name: Terraform Format
        working-directory: Environment/prod
        run: |
          terraform fmt -check -recursive

      # Terraform Validate
      - name: Terraform Validate
        working-directory: Environment/prod
        run: |
          terraform validate

      # Terraform Plan ONLY
      - name: Terraform Plan
        working-directory: Environment/prod
        run: |
          terraform plan -out=tfplan

      # Upload Plan
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: Environment/prod/tfplan